# flux-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: ./manifests  # path inside app-deploy-repo
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-repo
  targetNamespace: default
