# flux-gitrepo.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: app-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/eshwar3240/app-deploy-flux
  ref:
    branch: main
  secretRef:
    name: flux-git
