apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: app-repo
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: app-repo
  git:
    commit:
      author:
        email: eshwar@gmail.com
        name: fluxcdbot
    push:
      branch: main
  update:
    strategy: Setters
    path: manifests
  secretRef:
    name: flux-git-auth
