# image-update.yaml
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: app-auto
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: app-repo
  secretRef:                # ✅ Proper location
    name: flux-git-auth
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: flux-bot
        email: eshwar3240@gmail.com
    push:
      branch: main
    secretRef:
      name: flux-git-auth    
  update:
    strategy: Setters       
    path: ./manifests
