# image-repo.yaml
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: app-image
  namespace: flux-system
spec:
  image: eshwar0117/flux-cluster:1.0.0   # {"$imagepolicy": "flux-system:app-policy"}
  interval: 1m
