apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: app-es
  namespace: flux-system
spec:
  interval: 1m
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: fluxcdbot
        email: eshwar@gmail.com
    push:
      branch: main
  sourceRef:
    kind: GitRepository
    name: app-es
  update:
    strategy: Setters
    path: manifests
