apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: app-repo
  namespace: flux-system
spec:
  interval: 1m
  checkout:
    branch: main
    gitRepositoryRef:
      name: app-repo
    commit:
      author:
        name: fluxcdbot
        email: eshwar@gmail.com
    push:
      branch: main # <-- Move secretRef here!
  update:
    strategy: Setters
    path: manifests
