apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux-cluster-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flux-cluster-app
  template:
    metadata:
      labels:
        app: flux-cluster-app
    spec:
      containers:
        - name: app
          image: eshwar0117/flux-cluster:1.0.0    # {"$imagepolicy": "flux-system:app-policy"}
          ports:
            - containerPort: 5000
            