apiVersion: v1
kind: Service
metadata:
  name: flux-cluster-app
  namespace: default
spec:
  selector:
    app: flux-cluster-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000   # this must match the container's exposed port
      nodePort: 30080
