apiVersion: v1
kind: Service
metadata:
  name: flux-cluster-app
  namespace: default
spec:
  selector:
    app: flux-cluster-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort